# Generated by Django 3.2.6 on 2021-08-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATK_Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot_Number', models.IntegerField(blank=True, null=True, verbose_name='ล็อตที่')),
                ('Lot_Time', models.CharField(blank=True, max_length=10, null=True, verbose_name='เวลาที่นัดจอง')),
                ('Lot_Total', models.IntegerField(blank=True, default='', null=True, verbose_name='จำนวนผู้จอง')),
                ('Lot_Date', models.DateField(blank=True, null=True, verbose_name='วันที่ต้องการจอง')),
                ('Lot_Booking', models.CharField(choices=[('201', 'เต็ม'), ('202', 'ว่าง')], default='ว่าง', max_length=20, verbose_name='สถานะการจอง')),
            ],
            options={
                'verbose_name_plural': 'ตารางเวลาการตรวจ',
            },
        ),
        migrations.CreateModel(
            name='User_ATK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อ')),
                ('LastName', models.CharField(blank=True, max_length=200, null=True, verbose_name='นามสกุล')),
                ('Phone_Number', models.IntegerField(blank=True, null=True, verbose_name='เบอร์ติดต่อ')),
                ('BirthDay', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
            ],
            options={
                'verbose_name_plural': 'ผู้ลงทะเบียน',
            },
        ),
        migrations.CreateModel(
            name='ATK_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statas', models.CharField(choices=[('101', 'ยังไม่ได้เข้ารับบัตรคิว'), ('102', 'เข้ารับบัตรคิวแล้ว')], default='ยังไม่ได้เข้ารับบัตรคิว', max_length=20, verbose_name='สถานะเข้ารับบัตรคิว')),
                ('Queue', models.IntegerField(blank=True, null=True, verbose_name='คิวที่')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='เวลาที่บันทึก')),
                ('atk_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ATK_Lot_FK', to='Reserve.atk_lot')),
                ('user_atk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_ATK_FK', to='Reserve.user_atk')),
            ],
            options={
                'verbose_name_plural': 'การจัดการคิว',
                'ordering': ['id'],
            },
        ),
    ]
