# Generated by Django 3.2.6 on 2021-08-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เวลาที่นัดจอง'),
        ),
    ]
