# Generated by Django 3.2.6 on 2021-08-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0002_alter_atk_lot_lot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Booking',
            field=models.CharField(max_length=20, verbose_name='จำนวนที่จองไปแล้ว'),
        ),
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Total',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='จำนวนการเปิดจอง'),
        ),
    ]
