# Generated by Django 3.2.6 on 2021-08-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0003_auto_20210824_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Booking',
            field=models.IntegerField(verbose_name='จำนวนที่จองไปแล้ว'),
        ),
    ]
