# Generated by Django 3.2.6 on 2021-08-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0004_alter_atk_lot_lot_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_atk',
            name='BirthDay',
        ),
        migrations.RemoveField(
            model_name='user_atk',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='user_atk',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='user_atk',
            name='Phone_Number',
        ),
    ]
