# Generated by Django 3.2.6 on 2021-08-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0005_auto_20210824_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_queue',
            name='atk_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ATK_Lot_FK', to='Reserve.atk_lot', verbose_name='ล็อตที่'),
        ),
    ]
