# Generated by Django 3.2.6 on 2021-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0007_alter_user_atk_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_queue',
            name='Statas',
            field=models.CharField(choices=[('101', 'ยังไม่ได้รับการตรวจ'), ('102', 'ตรวจแล้ว')], default='ยังไม่ได้เข้ารับบัตรคิว', max_length=20, verbose_name='สถานะเข้ารับบัตรคิว'),
        ),
    ]
