# Generated by Django 3.2.5 on 2021-08-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0008_alter_atk_queue_statas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_queue',
            name='Statas',
            field=models.CharField(choices=[('101', 'ยังไม่ได้รับการตรวจ'), ('102', 'ตรวจแล้ว')], default='102', max_length=20, verbose_name='สถานะเข้ารับบัตรคิว'),
        ),
    ]
