# Generated by Django 3.2.5 on 2021-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0009_alter_atk_queue_statas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Date',
            field=models.DateField(blank=True, default='tomorrow', null=True, verbose_name='วันที่ต้องการจอง'),
        ),
        migrations.AlterField(
            model_name='atk_lot',
            name='Lot_Total',
            field=models.IntegerField(blank=True, default=200, null=True, verbose_name='จำนวนการเปิดจอง'),
        ),
    ]
