# Generated by Django 3.2.5 on 2021-08-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_unit_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ()},
        ),
    ]
